### ISSUE TITLE
Location of files

### ISSUE THREAD

**Issue by Bobpick** [Steelio/Telegram-Post-Scraper#1]
I am attempting to install the requirements.
It did not find the install.
I am using Windows 10 Powershell. New Python install. Pip has been upgraded.
Any suggestions where the directory where the scraper was put?

**Comment by Steelio** [comment]
> I am attempting to install the requirements. It did not find the install. I am using Windows 10 Powershell. New Python install. Pip has been upgraded. Any suggestions where the directory where the scraper was put?

Try altering the command line to pip3 and see if that works.
If that fails, try installing the requirements out of the text file manually.

The directory of the Scraper will be wherever "main.py" is located at and ran from. You determine this.

If you're still having issues, please feel free to follow up.
Attach any errors given by Powershell if possible.
