### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by bitter-fund** [Steelio/Telegram-Post-Scraper#2]
Every time I run it, it opens and asks for the telegram URL as expected. I paste in the URL and press enter and it returns:
AttributeError: 'NoneType' object has no attribute 'find'
All the files are in the same directory as described in a previous ticket. All requirements are installed (if I try to install them again using pip install -r requirements.txt it returns "requirements already satisfied" for each of the packages. 
I'm running on Windows 10

**Comment by Steelio** [comment]
This error typically occurs whenever you are attempting to parse a message that is within a private group, and or has specific privacy settings.
I'm able to reproduce the NoneType error via this route.

Check to verify that the post you're interacting with is available to normal public users, and not specific to its group members, as this is whenever I have the error raised as well.

If you still run into the NoneType error after trying to parse a public post, please report back with the full error. I'm more than happy to help figure this out for ya. :)
